package com.github.zeldigas.text2confl.cli

import com.github.zeldigas.confclient.ConfluenceClient
import com.github.zeldigas.confclient.ConfluenceClientConfig
import com.github.zeldigas.confclient.confluenceClient
import com.github.zeldigas.text2confl.cli.config.ConverterConfig
import com.github.zeldigas.text2confl.cli.config.UploadConfig
import com.github.zeldigas.text2confl.cli.export.PageExporter
import com.github.zeldigas.text2confl.cli.upload.ContentUploader
import com.github.zeldigas.text2confl.cli.upload.DryRunClient
import com.github.zeldigas.text2confl.convert.ConversionParameters
import com.github.zeldigas.text2confl.convert.Converter
import com.github.zeldigas.text2confl.convert.DEFAULT_AUTOGEN_BANNER
import com.github.zeldigas.text2confl.convert.universalConverter

interface ServiceProvider {
    fun createConverter(space: String, config: ConverterConfig): Converter
    fun createConfluenceClient(clientConfig: ConfluenceClientConfig, dryRun: Boolean): ConfluenceClient
    fun createUploader(
        client: ConfluenceClient,
        uploadConfig: UploadConfig,
        converterConfig: ConverterConfig
    ): ContentUploader
    fun createContentValidator(): ContentValidator
    fun createPageExporter(client: ConfluenceClient, saveContentSource: Boolean): PageExporter
}

class ServiceProviderImpl : ServiceProvider {
    override fun createConverter(space: String, config: ConverterConfig): Converter {
        return universalConverter(
            space = space,
            ConversionParameters(
                languageMapper = config.languageMapper,
                titleConverter = config.titleConverter,
                addAutogeneratedNote = config.addAutogeneratedNote ?: (config.docsLocation != null),
                docRootLocation = config.docsLocation ?: "",
                noteText = config.autogeneratedNote ?: DEFAULT_AUTOGEN_BANNER,
                markdownConfiguration = config.markdownConfig,
                asciidoctorConfiguration = config.asciidocConfig
            )
        )
    }

    override fun createConfluenceClient(clientConfig: ConfluenceClientConfig, dryRun: Boolean): ConfluenceClient {
        val client = confluenceClient(clientConfig)
        return if (dryRun) DryRunClient(client) else client
    }

    override fun createUploader(
        client: ConfluenceClient,
        uploadConfig: UploadConfig,
        converterConfig: ConverterConfig
    ): ContentUploader {
        return ContentUploader(
            client, uploadConfig.uploadMessage, uploadConfig.notifyWatchers,
            uploadConfig.modificationCheck,
            converterConfig.editorVersion, uploadConfig.removeOrphans,
            uploadConfig.tenant
        )
    }

    override fun createContentValidator(): ContentValidator {
        return ContentValidatorImpl()
    }

    override fun createPageExporter(client: ConfluenceClient, saveContentSource: Boolean): PageExporter {
        return PageExporter(client, saveContentSource)
    }
}