= AsciiDoc - Confluence specific features
:keywords: supported-format,asciidoc
:toc: preamble
:adocs_pass: https://docs.asciidoctor.org/asciidoc/latest/pass/pass-macro/

On this page you will find some non-standard features that were added to AsciiDoc in *text2confl*.
While they are Confluence specific, if Confluence is your main target for documentation uploads, you can use them without hesitation.

== Status macro

Status is a specific element that can serve as eye candy element for various reporting:
status:green[on track], status:grey[on hold], status:red[off track].

To insert it, use custom macro `+status:$color[$text_of_status]+`, where `$color` is valid color and `$text_of_status` is simple text that will be put in block, e.g. `+status:red[off track]+`.

NOTE: Only limited colors are supported, and you need to properly specify one of the following allowed values: `grey` , `red`, `green`, `purple`, `blue`.

== Mentioning user macro (Confluence Server only)

You can mention user using `+user:username[]+` macro, where `username` is your login in Confluence.
If you use email to log in, use it in macro: for example login \jsmith@example.org should be used as `+user:jsmith@example.org+[]`.

Unfortunately due to absence of human-readable usernames in Cloud edition this will work only on Server/Datacenter where human-readable usernames are still supported.

If you still need to mention user in Cloud, consider using <<raw-confluence-formatting,raw confluence markdown>>

== Putting date

To put a date that is rendered in fancy way in Confluence, standard html tag is used - `+<time datetime="YYYY-MM-DD"/>+`, e.g. +++<time datetime="2022-02-15" />+++.
You need to use link:{adocs_pass}[passthrough] to properly insert it, for example "triple plus" in paragraph.

TIP: If you need this date to be rendered by regular Asciidoc processors in addition to Confluence page, consider using more standard format of this tag by putting text inside time block: +++<time datetime="2022-02-15">Feb 15th</time>+++

== Confluence macros with simple options

Confluence has a lot of https://confluence.atlassian.com/doc/macros-139387.html[_macros_] - special gadgets that can add extra features to your confluence page.
While some of them has comprehensive configuration or can embed text content (like expand block), a lot of macros are as simple as macro keyword and a number of options that helps you configure behavior.

*text2confl* introduce adds custom _asciidoc macro_ that helps you to insert any Confluence macro that does not require complex parameters in simple way: `+confl_macro:MACRONAME[key1=value1 key2=value2]+`.

Values can be unquoted if they don't contain spaces, or you can put value in quotes if you have spaces -
`+confl_macro:MYMACRo[width=100 searchQuery="project in (A,B,C)"]+`.

[NOTE]
.Parameters for macros - how to find them?
====
Parameters are **not validated**, so make sure that you use expected params for your macro.
This can be done by adding the macro you need on sample page in WYSIWYG editor and then opening page in "storage format".
Macro name will be in `ac:structured-macro ac:name="MACRONAME"` block and all `ac:parameter ac:name="columns"` elements are macro parameters.

This is especially helpful for special hidden parameters like `serverId` in jira chart macro, that is GUID string and unique per jira server integration.
====

Some examples:

[cols=,a,a]
|===
|Type of macros |AsciiDoc |Result

|https://confluence.atlassian.com/doc/jira-issues-macro-139380.html#JiraIssuesMacro-Displayingasingleissue,orselectedissues[Reference to single jira ticket]
|`+confl_macro:jira[key=SI-1]+`
|confl_macro:jira[key=SI-1]

|https://confluence.atlassian.com/doc/jira-issues-macro-139380.html#JiraIssuesMacro-DisplayingissuesviaaJiraQueryLanguage(JQL)search[Jira report table]
|`+confl_macro:jira[jqlQuery="project = SI",columns="key,summary,assignee,reporter,status",maximumIssues=20]+`
| confl_macro:jira[jqlQuery="project = SI",columns="key,summary,assignee,reporter,status",maximumIssues=20]

|https://confluence.atlassian.com/doc/jira-chart-macro-427623467.html[Jira charts]
|`+confl_macro:jirachart[jql="project = SI",chartType=pie,statType=components,serverId="JIRA_SERVER_ID"]+`
|confl_macro:jirachart[jql="project = SI",chartType=pie,statType=components,serverId="JIRA_SERVER_ID"]
|===

[#raw-confluence-formatting]
== Adding raw confluence formatting

For complex cases, you can always generate raw html/confluence markup via {adocs_pass}[passthrough]

So these tags

[source,asciidoc]
----
++++
<ac:structured-macro ac:name="jira">
    <ac:parameter ac:name="columns">key,summary,assignee,reporter,status</ac:parameter>
    <ac:parameter ac:name="maximumIssues">20</ac:parameter>
    <ac:parameter ac:name="jqlQuery">project = SI</ac:parameter>
</ac:structured-macro>
++++
----

Will generate

++++
<ac:structured-macro ac:name="jira">
    <ac:parameter ac:name="columns">key,summary,assignee,reporter,status</ac:parameter>
    <ac:parameter ac:name="maximumIssues">20</ac:parameter>
    <ac:parameter ac:name="jqlQuery">project = SI</ac:parameter>
</ac:structured-macro>
++++