$schema: ./config.schema.json
server: https://text2conf.atlassian.net/wiki
space: docs
docs-location: https://github.com/zeldigas/text2confl/tree/master/docs/
title-prefix: "[text2confl] "
code-blocks:
  collapse-with-expand: false
additional-files-to-ignore:
  - CLAUDE.md
  - AGENTS.md